[package]
name = "lottery_mechine"
version = "1.0.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.7.11"
thiserror = "1.0.28"
spl-token = {version = "3.2.0", features = ["no-entrypoint"]}
arrayref = "0.3.6"
spl-associated-token-account = "1.0.3"
